<?php

/**
 * @file
 * Plugin definition.
 */
$plugin = array(
  'title' => t('SPnet Zebra'),
  'category' => t('SPnet'),
  'icon' => 'spnet_zebra.png',
  'theme' => 'panels_spnet_zebra',
  'css' => 'spnet_zebra.css',
  'regions' => array(
    'fluid1' => t('Fluid'),
    'container1' => t('Container'),
    'fluid2' => t('Fluid'),
    'container2' => t('Container'),
    'fluid3' => t('Fluid'),
    'container3' => t('Container'),
    'fluid4' => t('Fluid'),
    'container4' => t('Container'),
    'fluid5' => t('Fluid'),
    'container5' => t('Container'),
    'fluid6' => t('Fluid'),
    'container6' => t('Container'),
    'fluid7' => t('Fluid'),
    'container7' => t('Container'),
    'fluid8' => t('Fluid'),
    'container8' => t('Container'),
    'fluid9' => t('Fluid'),
    'container9' => t('Container'),
    'fluid10' => t('Fluid'),
    'container10' => t('Container'),
  ),
);
