<?php

/**
 * @file
 * Plugin definition.
 */
$plugin = array(
  'title' => t('SPnet Adaptive'),
  'category' => t('SPnet'),
  'icon' => 'spnet_adaptive.png',
  'theme' => 'panels_spnet_adaptive',
  'css' => 'spnet_adaptive.css',
  'regions' => array(
    'sidebar' => t('Sidebar'),
    'row1' => t('Row1'),
    'row2' => t('Row2'),
    'row3' => t('Row3'),
    'row4' => t('Row4'),
    'row5' => t('Row5'),
    'row6' => t('Row6'),
    'row7' => t('Row7'),
  ),
);
